"""
QLoRA Training script for the NLP Module.
Uses the 'trl' and 'peft' libraries to fine-tune Qwen2.5-7B on the Step-wise Pipeline dataset.
"""

import os
import torch
import json
from datasets import Dataset
try:
    from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig
    from peft import get_peft_model, LoraConfig as PeftLoraConfig, prepare_model_for_kbit_training
    from trl import SFTTrainer
except ImportError:
    print("Please install transformers, peft, trl, bitsandbytes, and datasets.")

from vinumqa.nlp_module.training.lora_config import LoraConfig, TrainingConfig

def load_formatted_dataset(json_path: str):
    """
    Load the formatted dataset generated by format_training_data.py
    """
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # We will format this into a single text column for SFTTrainer
    # Format: [INST] {instruction} {input} [/INST] {output}
    texts = []
    for sample in data:
        text = f"{sample['instruction']}\n\n{sample['input']}\n\n### Response\n{sample['output']}"
        texts.append(text)
        
    return Dataset.from_dict({"text": texts})

def train():
    # 1. Configs
    lora_cfg = LoraConfig()
    train_cfg = TrainingConfig()
    
    model_id = "Qwen/Qwen2.5-7B-Instruct"
    
    # 2. Load dataset
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(current_dir)))
    train_data_path = os.path.join(project_root, "vinumqa", "data", "train_split_formatted.json")
    
    if not os.path.exists(train_data_path):
        print(f"Training data not found at {train_data_path}. Please run format_training_data.py first.")
        return
        
    dataset = load_formatted_dataset(train_data_path)
    print(f"Loaded {len(dataset)} training samples.")
    
    # 3. Setup Quantization (4-bit QLoRA)
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16
    )
    
    # 4. Load Model and Tokenizer
    print(f"Loading {model_id} in 4-bit...")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )
    
    model = prepare_model_for_kbit_training(model)
    
    # 5. Setup LoRA
    peft_config = PeftLoraConfig(
        r=lora_cfg.r,
        lora_alpha=lora_cfg.lora_alpha,
        lora_dropout=lora_cfg.lora_dropout,
        bias=lora_cfg.bias,
        task_type=lora_cfg.task_type,
        target_modules=lora_cfg.target_modules
    )
    model = get_peft_model(model, peft_config)
    
    # 6. Training Arguments
    training_args = TrainingArguments(
        output_dir=train_cfg.output_dir,
        per_device_train_batch_size=train_cfg.per_device_train_batch_size,
        gradient_accumulation_steps=train_cfg.gradient_accumulation_steps,
        optim=train_cfg.optim,
        logging_steps=train_cfg.logging_steps,
        learning_rate=train_cfg.learning_rate,
        fp16=train_cfg.fp16,
        max_steps=train_cfg.max_steps,
        num_train_epochs=train_cfg.num_train_epochs,
        warmup_steps=train_cfg.warmup_steps,
        save_strategy="epoch",
    )
    
    # 7. Start Training
    trainer = SFTTrainer(
        model=model,
        train_dataset=dataset,
        peft_config=peft_config,
        dataset_text_field="text",
        max_seq_length=train_cfg.max_seq_length,
        tokenizer=tokenizer,
        args=training_args,
    )
    
    print("Starting training...")
    trainer.train()
    
    print(f"Saving final model to {train_cfg.output_dir}/final")
    trainer.model.save_pretrained(os.path.join(train_cfg.output_dir, "final"))

if __name__ == "__main__":
    # train()
    print("Train QLoRA script ready.")
