"""
QLoRA Training script for the NLP Module.
Uses the 'trl' and 'peft' libraries to fine-tune Qwen2.5-7B on the Step-wise Pipeline dataset.
"""

import os
import sys
import torch
import json
from pathlib import Path
from datasets import Dataset

# Reduce CUDA memory fragmentation (helps avoid OOM during eval's logits.float() cast)
os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")

# Add project root to sys.path to resolve vinumqa package
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

try:
    from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig
    from peft import get_peft_model, LoraConfig as PeftLoraConfig, prepare_model_for_kbit_training
except ImportError:
    raise ImportError("Install the project training dependencies")

from vinumqa.nlp_module.training.lora_config import LoraConfig, TrainingConfig
from vinumqa.nlp_module.contracts import FORMAT_VERSION, INSTRUCTION, RESPONSE_PREFIX
from vinumqa.nlp_module.training.supervision import encode_supervised, CompletionCollator, load_prepared_pair
from vinumqa.nlp_module.training.epoch_predictions import make_epoch_callback

def load_formatted_dataset(json_path: str, prepared_rows=None):
    """
    Load the formatted dataset generated by format_training_data.py
    """
    if prepared_rows is None:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = prepared_rows
        
    rows = []
    for sample in data:
        if sample.get("format_version") != FORMAT_VERSION or sample["instruction"] != INSTRUCTION:
            raise ValueError("Stale formatted dataset: regenerate with the v4 formatter and real CV")
        header = "| Step | Output |\n|---|---|\n"
        if not sample["output"].startswith(header): raise ValueError("Invalid completion format")
        rows.append({"prompt": sample["instruction"] + "\n\n" + sample["input"] + "\n\n" + RESPONSE_PREFIX,
                     "completion": sample["output"][len(header):]})
    return Dataset.from_list(rows)

def train(max_seq_length=8192, train_data_path=None, val_data_path=None, output_dir=None, skip_unready=False):
    # 1. Configs
    lora_cfg = LoraConfig()
    train_cfg = TrainingConfig()
    train_cfg.max_seq_length = max_seq_length
    if output_dir is not None:
        train_cfg.output_dir = str(output_dir)
    
    model_id = "Qwen/Qwen2.5-7B-Instruct"
    
    # 2. Load dataset
    train_data_path = str(Path(train_data_path).resolve() if train_data_path else PROJECT_ROOT / "vinumqa" / "data" / "train_formatted.json")
    val_data_path = str(Path(val_data_path).resolve() if val_data_path else PROJECT_ROOT / "vinumqa" / "data" / "public_test_formatted.json")
    
    train_rows, validation_rows = load_prepared_pair(train_data_path, val_data_path, skip_unready=skip_unready)
    print(f"Training from prepared JSON; no OCR required.\nTrain: {train_data_path}\nValidation: {val_data_path}")
        
    dataset = load_formatted_dataset(train_data_path, train_rows)
    print(f"Loaded {len(dataset)} training samples.")
    
    val_dataset = load_formatted_dataset(val_data_path, validation_rows)
    if val_dataset:
        print(f"Loaded {len(val_dataset)} validation samples (Public Test).")
    
    # 3. Setup Quantization (4-bit QLoRA)
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16
    )
    
    # 4. Load Model and Tokenizer
    print(f"Loading {model_id} in 4-bit...")
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token

    # Audit target lengths before allocating the model.
    def tokenize_function(example):
        return encode_supervised(tokenizer, example["prompt"], example["completion"], train_cfg.max_seq_length)
    tokenized_dataset = dataset.map(tokenize_function, remove_columns=["prompt", "completion"])
    tokenized_val_dataset = val_dataset.map(tokenize_function, remove_columns=["prompt", "completion"])
    
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True
    )
    
    model = prepare_model_for_kbit_training(model)
    
    # 5. Setup LoRA
    peft_config = PeftLoraConfig(
        r=lora_cfg.r,
        lora_alpha=lora_cfg.lora_alpha,
        lora_dropout=lora_cfg.lora_dropout,
        bias=lora_cfg.bias,
        task_type=lora_cfg.task_type,
        target_modules=lora_cfg.target_modules
    )
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()
    
    from transformers import Trainer

    training_args = TrainingArguments(
        output_dir=train_cfg.output_dir,
        per_device_train_batch_size=train_cfg.per_device_train_batch_size,
        per_device_eval_batch_size=train_cfg.per_device_eval_batch_size,
        gradient_accumulation_steps=train_cfg.gradient_accumulation_steps,
        eval_accumulation_steps=train_cfg.eval_accumulation_steps,
        optim=train_cfg.optim,
        logging_steps=train_cfg.logging_steps,
        learning_rate=train_cfg.learning_rate,
        fp16=train_cfg.fp16,
        max_steps=train_cfg.max_steps,
        num_train_epochs=train_cfg.num_train_epochs,
        warmup_steps=train_cfg.warmup_steps,
        save_strategy="epoch",
        eval_strategy="epoch" if tokenized_val_dataset else "no",
        gradient_checkpointing=True,
    )
    
    data_collator = CompletionCollator(tokenizer)

    # 7. Start Training
    trainer = Trainer(
        model=model,
        train_dataset=tokenized_dataset,
        eval_dataset=tokenized_val_dataset,
        args=training_args,
        data_collator=data_collator,
        callbacks=[make_epoch_callback(validation_rows, tokenizer)],
    )
    
    print("Starting training...")
    trainer.train()
    
    print(f"Saving final model to {train_cfg.output_dir}/final")
    final = Path(train_cfg.output_dir) / "final"
    trainer.model.save_pretrained(final)
    tokenizer.save_pretrained(final)
    import hashlib
    manifest = {"format_version": FORMAT_VERSION, "base_model": model_id,
        "prompt_sha256": hashlib.sha256(INSTRUCTION.encode()).hexdigest(),
        "train_sha256": hashlib.sha256(Path(train_data_path).read_bytes()).hexdigest(),
        "max_seq_length": train_cfg.max_seq_length}
    (final / "pipeline_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-seq-length", type=int, default=8192)
    parser.add_argument("--train-data", help="Prepared training JSON with embedded OCR Markdown")
    parser.add_argument("--val-data", help="Prepared public-test JSON with embedded OCR Markdown")
    parser.add_argument("--output-dir", help="Writable directory for checkpoints and epoch validation results")
    parser.add_argument("--skip-unready", action="store_true", help="Explicitly exclude failed/pending samples from train and validation")
    args = parser.parse_args()
    train(args.max_seq_length, args.train_data, args.val_data, args.output_dir, args.skip_unready)
