"""
Inference script to generate reasoning programs from text and tables using the fine-tuned NLP module.
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from vinumqa.nlp_module.inference.symbolic_executor import SymbolicExecutor
import re

class ProgramGenerator:
    def __init__(self, base_model_id: str = "Qwen/Qwen2.5-7B-Instruct", lora_weights: str = None, device: str = "cuda"):
        """
        Initialize the Program Generator (NLP Module).
        """
        self.device = device if torch.cuda.is_available() else "cpu"
        print(f"Loading {base_model_id} on {self.device}...")
        
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(base_model_id)
            self.model = AutoModelForCausalLM.from_pretrained(
                base_model_id,
                torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
                device_map="auto" if self.device == "cuda" else None
            )
            
            if lora_weights:
                print(f"Loading LoRA weights from {lora_weights}...")
                self.model = PeftModel.from_pretrained(self.model, lora_weights)
                
            self.model.eval()
            self.executor = SymbolicExecutor()
            print("NLP Module loaded successfully.")
        except Exception as e:
            print(f"Failed to load NLP module: {e}")
            self.model = None

    def generate(self, context_text: str, markdown_table: str, question: str) -> dict:
        """
        Generate a reasoning program and execute it.
        Returns a dict with 'extracted_values', 'program', and 'answer'.
        """
        if self.model is None:
            return {"error": "Model not loaded"}
            
        prompt = self._build_prompt(context_text, markdown_table, question)
        
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.device)
        
        try:
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=256,
                    temperature=0.0, # Greedy decoding for reasoning
                    do_sample=False
                )
            
            response_text = self.tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
            return self._parse_response(response_text)
            
        except Exception as e:
            return {"error": str(e)}

    def _build_prompt(self, context_text: str, markdown_table: str, question: str) -> str:
        """
        Build the prompt following the Step-wise Pipeline format.
        """
        instruction = (
            "### Instruction\n"
            "Step 1 - Extractor: Từ bảng và văn bản dưới đây, hãy trích xuất các giá trị số và thông tin liên quan để trả lời câu hỏi.\n"
            "Step 2 - Reasoner: Dựa trên các giá trị đã trích xuất, hãy sinh ra công thức tính toán dưới dạng reasoning program.\n\n"
            "Các hàm được phép: add, subtract, multiply, divide, greater, exp, table_max, table_min, table_sum, table_average, chart_at, chart_max, chart_min, chart_sum, chart_average\n"
            "Dùng #0, #1, ... để tham chiếu kết quả bước trước.\n\n"
        )
        
        context = ""
        if markdown_table:
            context += f"### Table\n{markdown_table}\n\n"
        if context_text:
            context += f"### Text\n{context_text}\n\n"
            
        context += f"### Question\n{question}\n\n### Response\n| Step | Output |\n|---|---|\n"
        
        return instruction + context

    def _parse_response(self, response_text: str) -> dict:
        """
        Parse the markdown table generated by the LLM to extract values and program.
        """
        result = {
            "extracted_values": "",
            "program": "",
            "answer": ""
        }
        
        # Simple extraction based on expected format
        lines = response_text.strip().split('\n')
        for line in lines:
            if line.startswith('| 1 |'):
                parts = line.split('|')
                if len(parts) >= 3:
                    result["extracted_values"] = parts[2].strip()
            elif line.startswith('| 2 |'):
                parts = line.split('|')
                if len(parts) >= 3:
                    result["program"] = parts[2].strip()
                    
        # Execute the program
        if result["program"]:
            result["answer"] = self.executor.execute(result["program"])
            
        return result

if __name__ == "__main__":
    # generator = ProgramGenerator()
    print("ProgramGenerator module is ready.")
